# Generated by Django 4.2.16 on 2025-05-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_contactpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='image',
        ),
        migrations.AddField(
            model_name='productgallery',
            name='image_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
