# Generated by Django 4.2.16 on 2025-05-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_remove_productgallery_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='image_filename',
        ),
        migrations.AddField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(default='', upload_to='products/gallery/'),
            preserve_default=False,
        ),
    ]
