# Generated by Django 4.2.16 on 2025-05-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_email_order_электрондық_пошта'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='review_text',
            field=models.TextField(blank=True),
        ),
    ]
